docker run -it -p 7000:8080 --rm \
 -e POLLEASE_DBPATH=$POLLEASE_DBPATH \
 -e POLLEASE_PAPERTRAIL_SERVER=$POLLEASE_PAPERTRAIL_SERVER \
 -e POLLEASE_PAPERTRAIL_PORT=$POLLEASE_PAPERTRAIL_PORT \
 -e POLLEASE_SLACK_AUTH_URL=$POLLEASE_SLACK_AUTH_URL \
 -e POLLEASE_SLACK_CLIENT_ID=$POLLEASE_SLACK_CLIENT_ID \
 -e POLLEASE_SLACK_CLIENT_SECRET=$POLLEASE_SLACK_CLIENT_SECRET \
 --name pollease_instance pollease
